version: '3.8'
services:
  pmap_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pmap_backend_container
    env_file:
        - ./.env.staging
    networks:
      - pmap_network
    ports:
      - ${BACKEND_PORT}:3001
  
  pmap_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pmap_frontend_container
    tty: true
    env_file:
        - ./.env.staging
    networks:
      - pmap_network
    ports:
      - ${FRONTEND_PORT}:3000
  
networks:
  pmap_network:
    name: pmap_network
