version: "3.8"
services:
  pmap_backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: pmap_backend_container
    env_file:
      - ./backend/src/.env.dev
    networks:
      - pmap_network
    ports:
      - ${BACKEND_PORT}:3001
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app

  mysql:
    image: mysql:8.0.36-debian
    container_name: ${MYSQL_CONTAINER_NAME}
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: unless-stopped
    working_dir: /var/lib/mysql
    command: --bind-address=0.0.0.0
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - pmap_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} && mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'show databases;'",
        ]
      timeout: 25s
      retries: 10
    networks:
      - pmap_network

  pmap_frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: pmap_frontend_container
    tty: true
    env_file:
      - ./frontend/.env.development
    networks:
      - pmap_network
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - pmap_backend

  # cache:
  #   extends:
  #     file: docker-compose.yml
  #     service: cache
  #   ports:
  #     - ${REDIS_PORT}:6379

  # mq: ...

  redis:
    image: redis:alpine
    container_name: pmap_redis_container
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - pmap-redis-volume:/data
    networks:
      - pmap_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  pmap_mysql_volume:
    name: ${MYSQL_VOLUME_PATH}
  pmap-redis-volume:
    name: ${REDIS_VOLUME_PATH}

networks:
  pmap_network:
    name: pmap_network
