version: '3.8'
services:
  pmap_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        CUSTOM_ENV: ${CUSTOM_ENV}
    container_name: pmap_backend_container
    env_file:
        - ./backend/src/.env.staging
    networks:
      - pmap_network
    ports:
      - ${BACKEND_PORT}:3001

  # pmap_frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: pmap_frontend_container
  #   env_file:
  #       - .env.production
  #   networks:
  #     - pmap_network
  #   ports:
  #     - ${FRONTEND_PORT}:...
  

  # cache:
  #   build:
  #     context: ./src/Database/Cache
  #   container_name: ${REDIS_CONTAINER_NAME}
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   volumes:
  #     - type: tmpfs
  #       target: /data
  #   networks:
  #     - pmap_network
  #   ports:
  #     - ${REDIS_PORT}:6379


  # mq: ...


  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pmap_network
    depends_on:
      - pmap_backend


networks:
  pmap_network:
    name: pmap_network
