version: '3.8'
services:
  pmap_backend:
    image: pmapnccu/pmap-backend-main:12431207095
    container_name: pmap_backend_container
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - LOGGING_ENABLED=${LOGGING_ENABLED}
    networks:
      - pmap_network
    ports:
      - ${BACKEND_PORT}:3001
  pmap_frontend:
    image: pmapnccu/pmap-frontend-main:12431207095
    container_name: pmap_frontend_container
    environment:
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_SOCKET_ORIGIN=${NEXT_PUBLIC_SOCKET_ORIGIN}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
      - BACKEND_API_URL=${BACKEND_API_URL}
    networks:
      - pmap_network
    ports:
      - ${FRONTEND_PORT}:3000
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/zerossl/certificate.crt:/etc/ssl/zerossl/certificate.crt
      - /etc/ssl/zerossl/private.key:/etc/ssl/zerossl/private.key
      - /etc/ssl/zerossl/ca_bundle.crt:/etc/ssl/zerossl/ca_bundle.crt
    networks:
      - pmap_network
    depends_on:
      - pmap_backend
networks:
  pmap_network:
    name: pmap_network
