version: '3.8'
services:
  pmap_backend:
    image: pmapnccu/pmap-backend-main:12569441289
    container_name: pmap-backend-container
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - LOGGING_ENABLED=${LOGGING_ENABLED}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
      - SNS_AWS_ACCESS_KEY=${SNS_AWS_ACCESS_KEY}
      - SNS_AWS_SECRET_ACCESS_KEY=${SNS_AWS_SECRET_ACCESS_KEY}
      - SNS_TOPIC_UPDATE_WEATHER=${SNS_TOPIC_UPDATE_WEATHER}
      - AWS_REGION=${AWS_REGION}
    networks:
      - pmap_network
    ports:
      - ${BACKEND_PORT}:3000
  pmap_frontend:
    image: pmapnccu/pmap-frontend-main:12569441289
    container_name: pmap-frontend-container
    environment:
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXT_PUBLIC_BACKEND_API_URL=${NEXT_PUBLIC_BACKEND_API_URL}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_SOCKET_ORIGIN=${NEXT_PUBLIC_SOCKET_ORIGIN}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
      - BACKEND_API_URL=${BACKEND_API_URL}
    networks:
      - pmap_network
    ports:
      - ${FRONTEND_PORT}:3000
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nginx/zerossl-challenge:/usr/share/nginx/html/zerossl-challenge:ro
      - /srv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/zerossl/certificate.crt:/etc/ssl/zerossl/certificate.crt
      - /etc/ssl/zerossl/private.key:/etc/ssl/zerossl/private.key
      - /etc/ssl/zerossl/ca_bundle.crt:/etc/ssl/zerossl/ca_bundle.crt
      - /etc/ssl/zerossl/fullchain.crt:/etc/ssl/zerossl/fullchain.crt
    networks:
      - pmap_network
    depends_on:
      - pmap_backend
  mq:
    image: eclipse-mosquitto
    container_name: pmap-mq-container
    ports:
      - "${MQ_PORT}:1883"
    volumes:
      - /srv/mq/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - pmap-mq-volume:/mosquitto/data:rw
      - pmap-mq-volume:/mosquitto/log:rw
    networks:
      - pmap_network
  redis:
    image: redis/redis-stack
    container_name: pmap-redis-container
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - pmap-redis-volume:/data
    networks:
      - pmap_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  notify_mail_sender:
    image: pmapnccu/pmap-mail-service-main:12569441289
    container_name: pmap-mail-sender-container
    restart: on-failure
    environment:
      - MQ_URL=${MQ_URL}
      - GMAIL_ACCOUNT=${GMAIL_ACCOUNT}
      - GMAIL_APP_PWD=${GMAIL_APP_PWD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
    networks:
      - pmap_network
    depends_on:
      mq:
        condition: service_started
  notify_socket_server:
    image: pmapnccu/pmap-socket-service-main:12569441289
    container_name: pmap-socket-server-container
    restart: on-failure
    environment:
      - MQ_URL=${MQ_URL}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - ${NOTIFY_SOCKET_PORT}:3002
    networks:
      - pmap_network
    depends_on:
      mq:
        condition: service_started
volumes:
  pmap-redis-volume:
    name: ${REDIS_VOLUME_PATH}
  pmap-mq-volume:
    name: ${MQ_VOLUME_PATH}
networks:
  pmap_network:
    name: pmap_network
