version: '3.8'
services:
  pmap_backend:
    image: pmapnccu/pmap-backend-main:12276579913
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - pmap_network
    ports:
      - ${BACKEND_PORT}:3001
  # pmap_frontend:
  #   image: pmapnccu/pmap-frontend-main:latest
  #   container_name: pmap_frontend_container
  #   environment:
  #       - 
  #   networks:
  #     - pmap_network
  #   ports:
  #     - ${FRONTEND_PORT}:...
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/zerossl/certificate.crt:/etc/ssl/zerossl/certificate.crt
      - /etc/ssl/zerossl/private.key:/etc/ssl/zerossl/private.key
      - /etc/ssl/zerossl/ca_bundle.crt:/etc/ssl/zerossl/ca_bundle.crt
    networks:
      - pmap_network
    depends_on:
      - pmap_backend
  backend:
    image: pmapnccu/pmap-backend-main:12276005870
networks:
  pmap_network:
    name: pmap_network
