name: Build Pipeline

on:
  push:
    branches:
      - main

env:
  CI_REGISTRY_IMAGE: pmapnccu/pmap

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Pull existing image for cache
        run: |
          docker pull ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.ref_name }}:latest || true

      - name: Build and push backend image
        run: |
          cd backend
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.ref_name }}:latest \
            -t ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.ref_name }}:${{ github.run_id }} \
            -t ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.ref_name }}:latest \
            .
          docker push ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.ref_name }}:${{ github.run_id }}
          docker push ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.ref_name }}:latest
    
  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Pull existing image for cache
        run: |
          docker pull ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.ref_name }}:latest || true

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.ref_name }}:latest \
            -t ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.ref_name }}:${{ github.run_id }} \
            -t ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.ref_name }}:latest \
            .
          docker push ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.ref_name }}:${{ github.run_id }}
          docker push ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.ref_name }}:latest
