name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    branches:
      - main
    types:
      - completed

permissions:
  contents: write

env:
  CI_REGISTRY_IMAGE: pmapnccu/pmap

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update docker-compose file
        env:
          BACKEND_IMAGE: ${{ env.CI_REGISTRY_IMAGE }}-backend-${{ github.event.workflow_run.head_branch }}:${{ github.event.workflow_run.id }}
          FRONTEND_IMAGE: ${{ env.CI_REGISTRY_IMAGE }}-frontend-${{ github.event.workflow_run.head_branch }}:${{ github.event.workflow_run.id }}
          MAIL_SERVICE_IMAGE: ${{ env.CI_REGISTRY_IMAGE }}-mail-service-${{ github.event.workflow_run.head_branch }}:${{ github.event.workflow_run.id }}
          SOCKET_SERVICE_IMAGE: ${{ env.CI_REGISTRY_IMAGE }}-socket-service-${{ github.event.workflow_run.head_branch }}:${{ github.event.workflow_run.id }}
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [ "${BRANCH_NAME}" == "main" ]; then
            DOCKER_COMPOSE_FILE="deploys/docker-compose-prod.yml"
          else
            echo "Unsupported branch: ${BRANCH_NAME}"
            exit 1
          fi
          yq e ".services.pmap_backend.image = \"${BACKEND_IMAGE}\"" -i ${DOCKER_COMPOSE_FILE}
          yq e ".services.pmap_frontend.image = \"${FRONTEND_IMAGE}\"" -i ${DOCKER_COMPOSE_FILE}
          yq e ".services.notify_mail_sender.image = \"${MAIL_SERVICE_IMAGE}\"" -i ${DOCKER_COMPOSE_FILE}
          yq e ".services.notify_socket_server.image = \"${SOCKET_SERVICE_IMAGE}\"" -i ${DOCKER_COMPOSE_FILE}

      - name: Commit and push changes
        env:
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add deploys/docker-compose-*.yml
          git commit -m "[bot] deploy docker-compose files with new images [skip ci]" || echo "No changes to commit"
          git push origin ${BRANCH_NAME}
      - name: Send Notification to Discord
        uses: appleboy/discord-action@master
        with:
            webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
            webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
            username: 'GitHub Bot'
            message: |
                **[Deploy]** Deployment completed on pmap.nccucloud.store. The **「${{ github.event_name }}」** event triggered by **「${{ github.actor }}」** on **${{ github.ref }}** succeeded.
